apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myreplicaset
  labels:
    app: goserver
    # key: value
spec:
  selector:
    matchLabels:
      app: goserver
  replicas: 2
  template:
    metadata:
      labels:
        app: goserver
        # key: value
    spec:
      containers:
        - name: goserver
          image: gusdevr/hello-go:latest
